const bcrypt = require("bcryptjs");

const pgUrl = process.env.DATABASE_URL || process.env.PG_URL;
const engine = pgUrl ? "postgresql" : "sqlite";
let client;

function pgSql(sql) {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
}

async function run(sql, params = []) {
  if (engine === "postgresql") {
    const statement = /^\s*insert\s/i.test(sql) && !/\breturning\b/i.test(sql)
      ? `${sql} RETURNING id`
      : sql;
    const result = await client.query(pgSql(statement), params);
    return {
      changes: result.rowCount,
      lastInsertRowid: result.rows[0]?.id,
    };
  }

  return client.prepare(sql).run(...params);
}

async function get(sql, params = []) {
  if (engine === "postgresql") {
    const result = await client.query(pgSql(sql), params);
    return result.rows[0] || null;
  }

  return client.prepare(sql).get(...params) || null;
}

async function all(sql, params = []) {
  if (engine === "postgresql") {
    const result = await client.query(pgSql(sql), params);
    return result.rows;
  }

  return client.prepare(sql).all(...params);
}

const db = {
  engine,
  prepare(sql) {
    return {
      run: (...params) => run(sql, params),
      get: (...params) => get(sql, params),
      all: (...params) => all(sql, params),
    };
  },
};

async function createSchema() {
  const id = engine === "postgresql"
    ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    : "INTEGER PRIMARY KEY AUTOINCREMENT";
  const now = "CURRENT_TIMESTAMP";

  const statements = [
    `CREATE TABLE IF NOT EXISTS usuarios (
      id ${id}, nome TEXT NOT NULL, email TEXT UNIQUE NOT NULL, senha TEXT NOT NULL,
      perfil TEXT NOT NULL DEFAULT 'marinheiro', avatar TEXT DEFAULT '',
      cargo TEXT DEFAULT '', embarcacao TEXT DEFAULT '', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS diario (
      id ${id}, usuario_id INTEGER NOT NULL, tipo TEXT NOT NULL, descricao TEXT NOT NULL,
      autor TEXT NOT NULL, assinado INTEGER DEFAULT 0, data TEXT DEFAULT '',
      hora TEXT DEFAULT '', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS checklist (
      id ${id}, usuario_id INTEGER NOT NULL, categoria TEXT NOT NULL, item TEXT NOT NULL,
      feito INTEGER DEFAULT 0, criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS tripulacao (
      id ${id}, nome TEXT NOT NULL, cargo TEXT NOT NULL, habilitacao TEXT DEFAULT '',
      certificado TEXT DEFAULT '', status TEXT DEFAULT 'ok', avatar TEXT DEFAULT '',
      criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS estoque (
      id ${id}, nome TEXT NOT NULL, unidade TEXT DEFAULT 'un', quantidade INTEGER DEFAULT 0,
      minimo INTEGER DEFAULT 0, categoria TEXT DEFAULT 'Geral', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS ordens_servico (
      id ${id}, codigo TEXT UNIQUE NOT NULL, embarcacao TEXT NOT NULL, cliente TEXT DEFAULT '',
      tipo TEXT DEFAULT 'Servico', prioridade TEXT DEFAULT 'normal', status TEXT DEFAULT 'aguardando',
      descricao TEXT DEFAULT '', responsavel TEXT DEFAULT '', abertura TEXT DEFAULT '',
      previsao TEXT DEFAULT '', fotos INTEGER DEFAULT 0, observacao TEXT DEFAULT '',
      criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS os_tarefas (
      id ${id}, os_id INTEGER NOT NULL, tarefa TEXT NOT NULL, done INTEGER DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS notificacoes (
      id ${id}, usuario_id INTEGER NOT NULL, tipo TEXT DEFAULT 'info', lida INTEGER DEFAULT 0,
      icone TEXT DEFAULT '', titulo TEXT NOT NULL, corpo TEXT DEFAULT '', acao TEXT DEFAULT '',
      categoria TEXT DEFAULT 'geral', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS bercos (
      id ${id}, numero TEXT UNIQUE NOT NULL, embarcacao TEXT DEFAULT '-',
      cliente TEXT DEFAULT '-', status TEXT DEFAULT 'livre', entrada TEXT DEFAULT '-', saida TEXT DEFAULT '-'
    )`,
  ];

  for (const statement of statements) {
    if (engine === "postgresql") await client.query(statement);
    else client.exec(statement);
  }
}

async function seed() {
  const count = await get("SELECT COUNT(*) AS total FROM usuarios");
  if (Number(count.total) > 0) return;

  const hash = bcrypt.hashSync("123456", 10);
  const users = [
    ["Carlos Mendes", "carlos@bordo.app", hash, "marinheiro", "CMD", "Capitao", "MV Esperanca"],
    ["Rafael Silva", "rafael@bordo.app", hash, "marinharia", "RS", "Tecnico de Marinharia", "Marina Sao Paulo"],
    ["Ana Costa", "ana@bordo.app", hash, "tecnico", "AC", "Mecanica Naval", "Estaleiro Litoral"],
    ["Admin Marina", "admin@bordo.app", hash, "gestor", "AM", "Gestor", "Marina Sao Paulo"],
  ];
  for (const values of users) {
    await run(
      "INSERT INTO usuarios (nome,email,senha,perfil,avatar,cargo,embarcacao) VALUES (?,?,?,?,?,?,?)",
      values,
    );
  }

  const crew = [
    ["Rafael Silva", "Marinheiro de Maquinas", "2025-08-10", "2026-01-15", "ok", "RS"],
    ["Carlos Mendes", "Capitao", "2024-12-01", "2025-11-20", "vencido", "CM"],
    ["Joao Ferreira", "Contramestre", "2026-03-20", "2026-06-01", "ok", "JF"],
    ["Ana Costa", "Cozinheira de Bordo", "2025-07-05", "2026-02-10", "alerta", "AC"],
  ];
  for (const values of crew) {
    await run(
      "INSERT INTO tripulacao (nome,cargo,habilitacao,certificado,status,avatar) VALUES (?,?,?,?,?,?)",
      values,
    );
  }

  const checklist = [
    [1, "Seguranca", "Coletes salva-vidas verificados", 1],
    [1, "Seguranca", "Sinalizadores dentro da validade", 1],
    [1, "Seguranca", "Extintor de incendio verificado", 0],
    [1, "Motor", "Nivel de oleo verificado", 1],
    [1, "Motor", "Sistema de refrigeracao OK", 1],
  ];
  for (const values of checklist) {
    await run("INSERT INTO checklist (usuario_id,categoria,item,feito) VALUES (?,?,?,?)", values);
  }

  const stock = [
    ["Oleo Motor 15W-40", "L", 12, 20, "Motor"],
    ["Filtro de combustivel", "un", 3, 2, "Motor"],
    ["Combustivel diesel", "L", 850, 300, "Combustivel"],
    ["Extintores reserva", "un", 1, 2, "Seguranca"],
  ];
  for (const values of stock) {
    await run("INSERT INTO estoque (nome,unidade,quantidade,minimo,categoria) VALUES (?,?,?,?,?)", values);
  }

  const orders = [
    ["OS-2026-041", "Lancha Brisa Mar", "Pedro Albuquerque", "Limpeza", "normal", "em_andamento", "Limpeza completa", "Rafael Silva", "13/06/2026", "13/06/2026"],
    ["OS-2026-039", "MV Esperanca", "Marina Sao Paulo", "Manutencao", "urgente", "aguardando", "Revisao do motor", "Carlos Mendes", "12/06/2026", "14/06/2026"],
  ];
  for (const values of orders) {
    await run(
      "INSERT INTO ordens_servico (codigo,embarcacao,cliente,tipo,prioridade,status,descricao,responsavel,abertura,previsao) VALUES (?,?,?,?,?,?,?,?,?,?)",
      values,
    );
  }

  await run("INSERT INTO os_tarefas (os_id,tarefa,done) VALUES (?,?,?)", [1, "Lavar casco", 1]);
  await run("INSERT INTO os_tarefas (os_id,tarefa,done) VALUES (?,?,?)", [1, "Limpar cabine", 0]);

  const berths = [
    ["01", "MV Esperanca", "Marina SP", "ocupado", "10/06", "16/06"],
    ["02", "Lancha Brisa Mar", "Pedro Albuquerque", "ocupado", "12/06", "14/06"],
    ["03", "-", "-", "livre", "-", "-"],
    ["04", "Veleiro Nautilus", "Ana Rodrigues", "ocupado", "11/06", "20/06"],
  ];
  for (const values of berths) {
    await run("INSERT INTO bercos (numero,embarcacao,cliente,status,entrada,saida) VALUES (?,?,?,?,?,?)", values);
  }

  await run(
    "INSERT INTO notificacoes (usuario_id,tipo,icone,titulo,corpo,acao,categoria) VALUES (?,?,?,?,?,?,?)",
    [1, "urgente", "!", "OS urgente - MV Esperanca", "Revisao do motor antes de zarpar.", "Ver OS", "os"],
  );
}

async function initialize() {
  if (engine === "postgresql") {
    const { Pool } = require("pg");
    client = new Pool({
      connectionString: pgUrl,
      ssl: process.env.PGSSLMODE === "disable" ? false : { rejectUnauthorized: false },
    });
  } else {
    const Database = require("better-sqlite3");
    const path = require("path");
    client = new Database(path.join(__dirname, "bordo.db"));
    client.pragma("journal_mode = WAL");
    client.pragma("foreign_keys = ON");
  }

  await createSchema();
  await seed();
  console.log(`Banco ${engine} pronto.`);
}

db.ready = initialize();
module.exports = db;
