const bcrypt = require("bcryptjs");
const path = require("path");

const pgUrl = process.env.DATABASE_URL || process.env.PG_URL;
const engine = pgUrl ? "postgresql" : "sqlite";
let client;

function pgSql(sql) {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
}

async function run(sql, params = []) {
  if (engine === "postgresql") {
    const statement = /^\s*insert\s/i.test(sql) && !/\breturning\b/i.test(sql)
      ? `${sql} RETURNING *`
      : sql;
    const result = await client.query(pgSql(statement), params);
    return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id };
  }
  return client.prepare(sql).run(...params);
}

async function get(sql, params = []) {
  if (engine === "postgresql") {
    const result = await client.query(pgSql(sql), params);
    return result.rows[0] || null;
  }
  return client.prepare(sql).get(...params) || null;
}

async function all(sql, params = []) {
  if (engine === "postgresql") {
    const result = await client.query(pgSql(sql), params);
    return result.rows;
  }
  return client.prepare(sql).all(...params);
}

const db = {
  engine,
  prepare(sql) {
    return {
      run: (...params) => run(sql, params),
      get: (...params) => get(sql, params),
      all: (...params) => all(sql, params),
    };
  },
};

async function execute(statement) {
  if (engine === "postgresql") await client.query(statement);
  else client.exec(statement);
}

async function hasColumn(table, column) {
  if (engine === "postgresql") {
    const row = await get(
      `SELECT 1 AS found
       FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = ? AND column_name = ?`,
      [table, column],
    );
    return Boolean(row);
  }
  const columns = await all(`PRAGMA table_info(${table})`);
  return columns.some((item) => item.name === column);
}

async function addColumn(table, definition) {
  const column = definition.trim().split(/\s+/)[0];
  if (await hasColumn(table, column)) return;
  await execute(`ALTER TABLE ${table} ADD COLUMN ${definition}`);
}

async function createSchema() {
  const id = engine === "postgresql"
    ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    : "INTEGER PRIMARY KEY AUTOINCREMENT";
  const now = "CURRENT_TIMESTAMP";

  const statements = [
    `CREATE TABLE IF NOT EXISTS schema_migrations (
      version TEXT PRIMARY KEY, aplicado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS empresas (
      id ${id}, nome TEXT NOT NULL, slug TEXT UNIQUE NOT NULL,
      plano TEXT NOT NULL DEFAULT 'trial', ativo INTEGER NOT NULL DEFAULT 1,
      criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS usuarios (
      id ${id}, empresa_id INTEGER, nome TEXT NOT NULL, email TEXT UNIQUE NOT NULL,
      senha TEXT NOT NULL, perfil TEXT NOT NULL DEFAULT 'marinheiro',
      papel TEXT NOT NULL DEFAULT 'membro', avatar TEXT DEFAULT '',
      cargo TEXT DEFAULT '', embarcacao TEXT DEFAULT '', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS diario (
      id ${id}, empresa_id INTEGER, usuario_id INTEGER NOT NULL, tipo TEXT NOT NULL,
      descricao TEXT NOT NULL, autor TEXT NOT NULL, assinado INTEGER DEFAULT 0,
      data TEXT DEFAULT '', hora TEXT DEFAULT '', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS checklist (
      id ${id}, empresa_id INTEGER, usuario_id INTEGER NOT NULL, categoria TEXT NOT NULL,
      item TEXT NOT NULL, feito INTEGER DEFAULT 0, criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS tripulacao (
      id ${id}, empresa_id INTEGER, nome TEXT NOT NULL, cargo TEXT NOT NULL,
      habilitacao TEXT DEFAULT '', certificado TEXT DEFAULT '', status TEXT DEFAULT 'ok',
      avatar TEXT DEFAULT '', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS estoque (
      id ${id}, empresa_id INTEGER, nome TEXT NOT NULL, unidade TEXT DEFAULT 'un',
      quantidade INTEGER DEFAULT 0, minimo INTEGER DEFAULT 0, categoria TEXT DEFAULT 'Geral',
      criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS ordens_servico (
      id ${id}, empresa_id INTEGER, codigo TEXT UNIQUE NOT NULL, embarcacao TEXT NOT NULL,
      cliente TEXT DEFAULT '', tipo TEXT DEFAULT 'Servico', prioridade TEXT DEFAULT 'normal',
      status TEXT DEFAULT 'aguardando', descricao TEXT DEFAULT '', responsavel TEXT DEFAULT '',
      abertura TEXT DEFAULT '', previsao TEXT DEFAULT '', fotos INTEGER DEFAULT 0,
      observacao TEXT DEFAULT '', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS os_tarefas (
      id ${id}, os_id INTEGER NOT NULL, tarefa TEXT NOT NULL, done INTEGER DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS notificacoes (
      id ${id}, empresa_id INTEGER, usuario_id INTEGER NOT NULL, tipo TEXT DEFAULT 'info',
      lida INTEGER DEFAULT 0, icone TEXT DEFAULT '', titulo TEXT NOT NULL, corpo TEXT DEFAULT '',
      acao TEXT DEFAULT '', categoria TEXT DEFAULT 'geral', criado_em TIMESTAMP DEFAULT ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS bercos (
      id ${id}, empresa_id INTEGER, numero TEXT NOT NULL, embarcacao TEXT DEFAULT '-',
      cliente TEXT DEFAULT '-', status TEXT DEFAULT 'livre', entrada TEXT DEFAULT '-',
      saida TEXT DEFAULT '-'
    )`,
  ];

  for (const statement of statements) await execute(statement);
}

async function migrateTenantColumns() {
  await addColumn("usuarios", "empresa_id INTEGER");
  await addColumn("usuarios", "papel TEXT NOT NULL DEFAULT 'membro'");

  for (const table of [
    "diario",
    "checklist",
    "tripulacao",
    "estoque",
    "ordens_servico",
    "notificacoes",
    "bercos",
  ]) {
    await addColumn(table, "empresa_id INTEGER");
  }

  let empresa = await get("SELECT id FROM empresas ORDER BY id LIMIT 1");
  if (!empresa) {
    const result = await run(
      "INSERT INTO empresas (nome, slug, plano) VALUES (?, ?, ?)",
      ["BORDO Demonstracao", "bordo-demonstracao", "trial"],
    );
    empresa = { id: result.lastInsertRowid };
  }

  await run("UPDATE usuarios SET empresa_id = ? WHERE empresa_id IS NULL", [empresa.id]);
  await run(
    `UPDATE usuarios
     SET papel = CASE WHEN perfil = 'gestor' THEN 'proprietario' ELSE 'membro' END
     WHERE papel IS NULL OR papel = '' OR (papel = 'membro' AND perfil = 'gestor')`,
  );

  for (const table of [
    "diario",
    "checklist",
    "tripulacao",
    "estoque",
    "ordens_servico",
    "notificacoes",
    "bercos",
  ]) {
    await run(`UPDATE ${table} SET empresa_id = ? WHERE empresa_id IS NULL`, [empresa.id]);
  }

  if (engine === "postgresql") {
    await execute("CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON usuarios (empresa_id)");
    await execute("CREATE INDEX IF NOT EXISTS idx_ordens_empresa ON ordens_servico (empresa_id)");
    await execute("CREATE INDEX IF NOT EXISTS idx_estoque_empresa ON estoque (empresa_id)");
    await execute("CREATE INDEX IF NOT EXISTS idx_tripulacao_empresa ON tripulacao (empresa_id)");
    await execute("CREATE INDEX IF NOT EXISTS idx_bercos_empresa ON bercos (empresa_id)");
  }
}

async function seed() {
  const count = await get("SELECT COUNT(*) AS total FROM usuarios");
  if (Number(count.total) > 0) return;

  const empresa = await get("SELECT id FROM empresas ORDER BY id LIMIT 1");
  const empresaId = empresa.id;
  const hash = bcrypt.hashSync("123456", 10);
  const users = [
    [empresaId, "Carlos Mendes", "carlos@bordo.app", hash, "marinheiro", "membro", "CMD", "Capitao", "MV Esperanca"],
    [empresaId, "Rafael Silva", "rafael@bordo.app", hash, "marinharia", "membro", "RS", "Tecnico de Marinharia", "Marina Sao Paulo"],
    [empresaId, "Ana Costa", "ana@bordo.app", hash, "tecnico", "tecnico", "AC", "Mecanica Naval", "Estaleiro Litoral"],
    [empresaId, "Admin Marina", "admin@bordo.app", hash, "gestor", "proprietario", "AM", "Gestor", "Marina Sao Paulo"],
  ];
  for (const values of users) {
    await run(
      `INSERT INTO usuarios
       (empresa_id,nome,email,senha,perfil,papel,avatar,cargo,embarcacao)
       VALUES (?,?,?,?,?,?,?,?,?)`,
      values,
    );
  }

  const crew = [
    ["Rafael Silva", "Marinheiro de Maquinas", "2025-08-10", "2026-01-15", "ok", "RS"],
    ["Carlos Mendes", "Capitao", "2024-12-01", "2025-11-20", "vencido", "CM"],
    ["Joao Ferreira", "Contramestre", "2026-03-20", "2026-06-01", "ok", "JF"],
    ["Ana Costa", "Cozinheira de Bordo", "2025-07-05", "2026-02-10", "alerta", "AC"],
  ];
  for (const values of crew) {
    await run(
      `INSERT INTO tripulacao
       (empresa_id,nome,cargo,habilitacao,certificado,status,avatar)
       VALUES (?,?,?,?,?,?,?)`,
      [empresaId, ...values],
    );
  }

  const checklist = [
    [1, "Seguranca", "Coletes salva-vidas verificados", 1],
    [1, "Seguranca", "Sinalizadores dentro da validade", 1],
    [1, "Seguranca", "Extintor de incendio verificado", 0],
    [1, "Motor", "Nivel de oleo verificado", 1],
    [1, "Motor", "Sistema de refrigeracao OK", 1],
  ];
  for (const values of checklist) {
    await run(
      "INSERT INTO checklist (empresa_id,usuario_id,categoria,item,feito) VALUES (?,?,?,?,?)",
      [empresaId, ...values],
    );
  }

  const stock = [
    ["Oleo Motor 15W-40", "L", 12, 20, "Motor"],
    ["Filtro de combustivel", "un", 3, 2, "Motor"],
    ["Combustivel diesel", "L", 850, 300, "Combustivel"],
    ["Extintores reserva", "un", 1, 2, "Seguranca"],
  ];
  for (const values of stock) {
    await run(
      `INSERT INTO estoque
       (empresa_id,nome,unidade,quantidade,minimo,categoria)
       VALUES (?,?,?,?,?,?)`,
      [empresaId, ...values],
    );
  }

  const orders = [
    ["OS-2026-041", "Lancha Brisa Mar", "Pedro Albuquerque", "Limpeza", "normal", "em_andamento", "Limpeza completa", "Rafael Silva", "13/06/2026", "13/06/2026"],
    ["OS-2026-039", "MV Esperanca", "Marina Sao Paulo", "Manutencao", "urgente", "aguardando", "Revisao do motor", "Carlos Mendes", "12/06/2026", "14/06/2026"],
  ];
  const orderIds = [];
  for (const values of orders) {
    const result = await run(
      `INSERT INTO ordens_servico
       (empresa_id,codigo,embarcacao,cliente,tipo,prioridade,status,descricao,responsavel,abertura,previsao)
       VALUES (?,?,?,?,?,?,?,?,?,?,?)`,
      [empresaId, ...values],
    );
    orderIds.push(result.lastInsertRowid);
  }

  await run("INSERT INTO os_tarefas (os_id,tarefa,done) VALUES (?,?,?)", [orderIds[0], "Lavar casco", 1]);
  await run("INSERT INTO os_tarefas (os_id,tarefa,done) VALUES (?,?,?)", [orderIds[0], "Limpar cabine", 0]);

  const berths = [
    ["01", "MV Esperanca", "Marina SP", "ocupado", "10/06", "16/06"],
    ["02", "Lancha Brisa Mar", "Pedro Albuquerque", "ocupado", "12/06", "14/06"],
    ["03", "-", "-", "livre", "-", "-"],
    ["04", "Veleiro Nautilus", "Ana Rodrigues", "ocupado", "11/06", "20/06"],
  ];
  for (const values of berths) {
    await run(
      `INSERT INTO bercos
       (empresa_id,numero,embarcacao,cliente,status,entrada,saida)
       VALUES (?,?,?,?,?,?,?)`,
      [empresaId, ...values],
    );
  }

  await run(
    `INSERT INTO notificacoes
     (empresa_id,usuario_id,tipo,icone,titulo,corpo,acao,categoria)
     VALUES (?,?,?,?,?,?,?,?)`,
    [empresaId, 1, "urgente", "!", "OS urgente - MV Esperanca", "Revisao do motor antes de zarpar.", "Ver OS", "os"],
  );
}

async function initialize() {
  if (engine === "postgresql") {
    const { Pool } = require("pg");
    client = new Pool({
      connectionString: pgUrl,
      ssl: process.env.PGSSLMODE === "disable" ? false : { rejectUnauthorized: false },
    });
  } else {
    const Database = require("better-sqlite3");
    const dbPath = process.env.BORDO_DB_PATH || path.join(__dirname, "bordo.db");
    client = new Database(dbPath);
    client.pragma("journal_mode = WAL");
    client.pragma("foreign_keys = ON");
  }

  await createSchema();
  const migration = await get(
    "SELECT version FROM schema_migrations WHERE version = ?",
    ["001_multi_tenant"],
  );
  if (!migration) {
    await migrateTenantColumns();
    await run(
      "INSERT INTO schema_migrations (version) VALUES (?)",
      ["001_multi_tenant"],
    );
  }
  await seed();
  console.log(`Banco ${engine} pronto.`);
}

db.ready = initialize();
module.exports = db;
